import type { Listing, HouseSubType, PetPolicy } from "./types";

export const NIGERIAN_STATES: string[] = [
  "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa",
  "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo",
  "Ekiti", "Enugu", "FCT (Abuja)", "Gombe", "Imo", "Jigawa",
  "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara",
  "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun",
  "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"
];

export const STATE_CITIES: Record<string, string[]> = {
  "Abia": ["Aba", "Umuahia", "Arochukwu", "Ohafia"],
  "Adamawa": ["Yola", "Mubi", "Jimeta", "Numan"],
  "Akwa Ibom": ["Uyo", "Ikot Ekpene", "Eket", "Oron"],
  "Anambra": ["Awka", "Onitsha", "Nnewi", "Aguata"],
  "Bauchi": ["Bauchi", "Azare", "Misau", "Jama'are"],
  "Bayelsa": ["Yenagoa", "Brass", "Sagbama", "Ogbia"],
  "Benue": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala"],
  "Borno": ["Maiduguri", "Biu", "Bama", "Damboa"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Ugep"],
  "Delta": ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"],
  "Ebonyi": ["Abakaliki", "Afikpo", "Onueke", "Ishielu"],
  "Edo": ["Benin City", "Auchi", "Ekpoma", "Uromi"],
  "Ekiti": ["Ado Ekiti", "Ikere Ekiti", "Omuo", "Aramoko"],
  "Enugu": ["Enugu", "Nsukka", "Oji River", "Udi"],
  "FCT (Abuja)": ["Maitama", "Wuse", "Garki", "Gwarinpa", "Kubwa", "Asokoro"],
  "Gombe": ["Gombe", "Kumo", "Bajoga", "Deba"],
  "Imo": ["Owerri", "Orlu", "Okigwe", "Mbaise"],
  "Jigawa": ["Dutse", "Hadejia", "Kazaure", "Birnin Kudu"],
  "Kaduna": ["Kaduna", "Zaria", "Kafanchan", "Saminaka"],
  "Kano": ["Kano", "Wudil", "Bichi", "Rano"],
  "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Yelwa", "Zuru"],
  "Kogi": ["Lokoja", "Okene", "Kabba", "Idah"],
  "Kwara": ["Ilorin", "Offa", "Jebba", "Omu-Aran"],
  "Lagos": ["Ikeja", "Lekki", "Victoria Island", "Surulere", "Epe", "Ikorodu", "Yaba", "Ajah"],
  "Nasarawa": ["Lafia", "Keffi", "Akwanga", "Karshi"],
  "Niger": ["Minna", "Suleja", "Bida", "Kontagora"],
  "Ogun": ["Abeokuta", "Sagamu", "Ijebu Ode", "Otta", "Mowe"],
  "Ondo": ["Akure", "Ondo City", "Owo", "Okitipupa"],
  "Osun": ["Osogbo", "Ilesa", "Ife", "Ila-Orangun"],
  "Oyo": ["Ibadan", "Ogbomoso", "Oyo Town", "Saki", "Iseyin"],
  "Plateau": ["Jos", "Bukuru", "Pankshin", "Shendam"],
  "Rivers": ["Port Harcourt", "Bonny", "Eleme", "Omoku"],
  "Sokoto": ["Sokoto", "Wamakko", "Tambuwal", "Gwadabawa"],
  "Taraba": ["Jalingo", "Wukari", "Serti", "Bali"],
  "Yobe": ["Damaturu", "Potiskum", "Gashua", "Nguru"],
  "Zamfara": ["Gusau", "Kaura Namoda", "Anka", "Talata Mafara"]
};

export const HOUSE_SUB_TYPES: HouseSubType[] = [
  "Duplex", "Bungalow", "Block of Flats", "Penthouse", "Terrace", "Semi-Detached", "Detached"
];

export const HOUSE_AMENITIES = [
  "Balcony", "Garden", "Car Park / Parking Space", "Dining Area", "Laundry Room", "Store / Pantry", "Penthouse Suite Access"
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "lst-001",
    title: "Modern 3-Bedroom Terrace Duplex",
    price: 85000000,
    status: "SALE",
    city: "Lekki",
    state: "Lagos",
    propertyType: "House",
    houseSubType: "Terrace",
    bedrooms: 3,
    bathrooms: 4,
    kitchenCount: 1,
    amenities: ["Kitchen", "Car Park / Parking Space", "Garden", "Security"],
    petPolicy: "Pets Allowed",
    sizeSqm: 220,
    description:
      "A newly built terrace duplex in a serene estate with 24/7 security, ample parking space, and modern finishes. The kitchen comes fully fitted with quality cabinets and appliances. All rooms are ensuite with fitted wardrobes.",
    features: ["C of O", "Electricity", "Water", "Security"],
    images: [
      "https://images.unsplash.com/photo-1564013799936-ab5827c0c558?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c0c9a01?w=1200&q=80",
    ],
    ownerName: "Chidi Okafor",
    ownerPhone: "+2348012345678",
    ownerWhatsapp: "2348012345678",
    postedAt: "2024-01-15",
  },
  {
    id: "lst-002",
    title: "Luxury 4-Bedroom Detached House",
    price: 250000000,
    status: "SALE",
    city: "Maitama",
    state: "FCT (Abuja)",
    propertyType: "House",
    houseSubType: "Detached",
    bedrooms: 4,
    bathrooms: 5,
    kitchenCount: 2,
    amenities: ["Swimming Pool", "Gym", "Smart Home", "Car Park / Parking Space", "Garden", "Laundry Room"],
    petPolicy: "On Request",
    sizeSqm: 450,
    description:
      "Exquisite detached home in the heart of Maitama. Features a swimming pool, gym, and smart home automation. The property sits on a large plot with beautifully landscaped gardens.",
    features: ["C of O", "Electricity", "Water"],
    images: [
      "https://images.unsplash.com/photo-1613490493576-88fda9c1c60d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db54?w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&q=80",
    ],
    ownerName: "Aisha Bello",
    ownerPhone: "+2348023456789",
    ownerWhatsapp: "2348023456789",
    postedAt: "2024-02-20",
  },
  {
    id: "lst-003",
    title: "Cozy 2-Bedroom Apartment for Rent",
    price: 1500000,
    status: "RENT",
    city: "Yaba",
    state: "Lagos",
    propertyType: "House",
    houseSubType: "Block of Flats",
    bedrooms: 2,
    bathrooms: 2,
    kitchenCount: 1,
    amenities: ["Car Park / Parking Space", "Borehole", "Dining Area"],
    petPolicy: "No Pets Allowed",
    sizeSqm: 95,
    description:
      "Well-maintained 2-bedroom apartment in a quiet neighborhood. Close to shops, schools, and public transport. Perfect for young professionals or small families.",
    features: ["Electricity", "Water"],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d9e578?w=1200&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80",
    ],
    ownerName: "Funke Adeyemi",
    ownerPhone: "+2348034567890",
    ownerWhatsapp: "2348034567890",
    postedAt: "2024-03-05",
  },
  {
    id: "lst-004",
    title: "Prime Commercial Land (1 Acre)",
    price: 120000000,
    status: "SALE",
    city: "Ibadan",
    state: "Oyo",
    propertyType: "Land",
    amenities: [],
    petPolicy: "Pets Allowed",
    sizeSqm: 4047,
    description:
      "Strategically located commercial land suitable for shopping mall, office complex, or mixed-use development. Directly facing the main road with high traffic visibility.",
    features: ["C of O", "Electricity", "Fenced", "Good Road Network"],
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c50?w=1200&q=80",
    ],
    ownerName: "Kunle Raji",
    ownerPhone: "+2348045678901",
    ownerWhatsapp: "2348045678901",
    postedAt: "2024-03-10",
  },
  {
    id: "lst-005",
    title: "Office Space for Lease (Open Plan)",
    price: 5000000,
    status: "LEASE",
    city: "Victoria Island",
    state: "Lagos",
    propertyType: "Commercial",
    amenities: [],
    petPolicy: "No Pets Allowed",
    sizeSqm: 180,
    description:
      "Modern open-plan office space in a Grade A building. Comes with fitted kitchen, server room, and ample parking. Flexible lease terms available.",
    features: ["Electricity", "Water", "24/7 Security", "Air Conditioning", "Server Room"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870743d04b2?w=1200&q=80",
    ],
    ownerName: "Tunde Bakare",
    ownerPhone: "+2348056789012",
    ownerWhatsapp: "2348056789012",
    postedAt: "2024-03-15",
  },
  {
    id: "lst-006",
    title: "5-Bedroom Contemporary Mansion",
    price: 180000000,
    status: "SALE",
    city: "Ikeja GRA",
    state: "Lagos",
    propertyType: "House",
    houseSubType: "Duplex",
    bedrooms: 5,
    bathrooms: 6,
    kitchenCount: 2,
    amenities: ["Home Cinema", "Swimming Pool", "Gym", "Smart Home", "Garden", "Car Park / Parking Space", "Laundry Room", "Balcony"],
    petPolicy: "Pets Allowed",
    sizeSqm: 600,
    description:
      "Stunning contemporary mansion with state-of-the-art amenities. Features include a home cinema, indoor pool, and private gym. Located in the prestigious Ikeja GRA.",
    features: ["C of O", "Electricity", "Water"],
    images: [
      "https://images.unsplash.com/photo-1600585154363-67eb9e5e224a?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18f6c1f1f?w=1200&q=80",
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&q=80",
    ],
    ownerName: "Ngozi Eze",
    ownerPhone: "+2348067890123",
    ownerWhatsapp: "2348067890123",
    postedAt: "2024-03-20",
  },
  {
    id: "lst-007",
    title: "Standard 600sqm Plot of Land",
    price: 25000000,
    status: "SALE",
    city: "Lekki",
    state: "Lagos",
    propertyType: "Land",
    amenities: [],
    petPolicy: "Pets Allowed",
    sizeSqm: 600,
    description:
      "Dry and well-located plot of land in Lekki Phase 1. Suitable for residential development. Has genuine title documents and is free from encumbrances.",
    features: ["C of O", "Dry Land", "Fenced", "Good Road"],
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c50?w=1200&q=80",
    ],
    ownerName: "Emeka Nwosu",
    ownerPhone: "+2348078901234",
    ownerWhatsapp: "2348078901234",
    postedAt: "2024-03-25",
  },
  {
    id: "lst-008",
    title: "3-Bedroom Flat for Rent (Serviced)",
    price: 4500000,
    status: "RENT",
    city: "Wuse",
    state: "FCT (Abuja)",
    propertyType: "House",
    houseSubType: "Block of Flats",
    bedrooms: 3,
    bathrooms: 3,
    kitchenCount: 1,
    amenities: ["Air Conditioning", "Car Park / Parking Space", "Security", "Serviced", "Balcony", "Store / Pantry"],
    petPolicy: "On Request",
    sizeSqm: 160,
    description:
      "Fully serviced 3-bedroom flat in a secure compound. Comes with fitted kitchen, air conditioning, and dedicated parking. Rent includes service charges.",
    features: ["Electricity", "Water"],
    images: [
      "https://images.unsplash.com/photo-1560448204-e02b11c4307c?w=1200&q=80",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80",
    ],
    ownerName: "Zainab Ibrahim",
    ownerPhone: "+2348089012345",
    ownerWhatsapp: "2348089012345",
    postedAt: "2024-04-01",
  },
];